[tool.poetry]
name = "yvis"
version = "0.1.0"
description = "yvis"
authors = ["Yvictor <yvictor3141@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
